#!/bin/bash -e

echo "Zero free space on /"
dd if=/dev/zero of=/EMPTY bs=1M || true
rm -f /EMPTY

echo "Zero free space on /tmp"
count=$(df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}')
let count--
dd if=/dev/zero of=/tmp/whitespace bs=1024 count=$count || true
rm /tmp/whitespace

echo "Zero free space on /boot"
count=$(df --sync -kP /boot | tail -n1 | awk -F ' ' '{print $4}')
let count--
dd if=/dev/zero of=/boot/whitespace bs=1024 count=$count || true
rm /boot/whitespace

echo "Zero free space on swap"
swappart=$(cat /proc/swaps | grep -v Filename | tail -n1 | awk -F ' ' '{print $1}')
if [ "$swappart" != "" ]; then
  swapoff $swappart
  dd if=/dev/zero of=$swappart || true
  mkswap $swappart
  swapon $swappart
fi
